### ISSUE TITLE
Issue when generating samples

### ISSUE THREAD

**Issue by mriganktiwari** [facebookresearch/TreeNLG#8]
When I try to use below command:
```bash scripts/generate.weather.lstm.sh```

I get this error:
 ```0%|                                                                                                                                                                                 | 0/25 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/mrigank/miniconda3/bin/fairseq-generate", line 33, in <module>
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-generate')())
  File "/home/mrigank/code/TreeNLG/fairseq/fairseq_cli/generate.py", line 285, in cli_main
    main(args)
  File "/home/mrigank/code/TreeNLG/fairseq/fairseq_cli/generate.py", line 38, in main
    return _main(args, sys.stdout)
  File "/home/mrigank/code/TreeNLG/fairseq/fairseq_cli/generate.py", line 126, in _main
    generator = task.build_generator(models, args)
TypeError: build_generator() takes 2 positional arguments but 3 were given
Args ::  Namespace(order_constr=False, tsv='scripts/tmp/tsv')                                                                                                                                                
Number of lines:  []
Traceback (most recent call last):
  File "compute_tree_acc.py", line 31, in <module>
    correct / len(lines) * 100, correct, len(lines)
ZeroDivisionError: division by zero
Runtime error (func=(main), adr=3): Divide by zero
Failure rate: 0.00 (0 / 0)

replacing failures from /home/mrigank/code/TreeNLG/checkpoints/weather.lstm/gen.txt
/home/mrigank/code/TreeNLG/checkpoints/weather.lstm/gen.txt does not exist```

**Comment by znculee** [comment]
According to `TypeError: build_generator() takes 2 positional arguments but 3 were given`, perhaps you are using a different fairseq version. Did you follow the [instructions](https://github.com/facebookresearch/TreeNLG#constrained-decoding) in the README? You may have to change the fairseq to commit `3822db3`. To do this, you may have to locally install fairseq with `pip install -e`.

**Comment by mriganktiwari** [comment]
Yes, using the specified commit helped, thanks!
